name: ssb
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
        
      - name: 安装依赖并运行脚本
        run: |
          pip install beautifulsoup4 requests
          python ssb.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add xin_Discuz.js
          git add ziti.js
          git diff --quiet && git diff --staged --quiet || git commit -m "Update xin_Discuz.js match URL"
          git push
